name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions: {}

jobs:
  candidate_release:
    name: Release candidate on Github for review
    runs-on: ubuntu-latest
    permissions:
      contents: write # to modify GitHub releases
    outputs:
      release_id: ${{ steps.gh-release.outputs.id }}
    steps:

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - id: github-release
        name: Publish GitHub release candidate
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            console.log('${{ github.ref }}')
            console.log('${{ github.ref_name }}-draft')
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ github.ref }}',
              name: '${{ github.ref_name }}-draft'
              draft: true,
            });
            
